version: '3.8'

services:
  react:
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    volumes: 
      - ./:/app
      - ./node_modules:/app/node_modules

